remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
title: "nisedo"
description: "Blockchain Security Researcher"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

github:
  is_project_page: false
show_downloads: false

include:
  - _layouts
  - _includes
  - _data
